import type { Metadata } from "next";
import { Texturina } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { TooltipProvider } from "@/components/ui/tooltip";

import { AuthProvider } from "@/components/Providers";
import BackgroundPattern from "@/components/BackgroundPattern";
import DockNav from "@/components/DockNav";

const winkRough = Texturina({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${winkRough.className} relative`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <TooltipProvider>
              <BackgroundPattern />
              <main className="pb-32">{children}</main>
              <DockNav />
            </TooltipProvider>
          </AuthProvider>
          <ToastContainer
            autoClose={2000}
            position="top-right"
            theme="light"
            closeOnClick={true}
            pauseOnHover={true}
            hideProgressBar={false}
            newestOnTop={true}
            transition={Slide}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
